import { Globe2, Hammer, ShieldCheck, Users } from 'lucide-react';

const stats = [{ value: '30+', label: 'Years of experience' }, { value: '10,000+', label: 'Happy clients' }, { value: '15–20+', label: 'Completed projects' }, { value: '₹70 Cr', label: 'Annual turnover' }];

export default function About() {
  return (
    <section id="about" className="bg-white py-20 md:py-28"><div className="mx-auto max-w-7xl px-4 md:px-6"><div className="grid grid-cols-1 gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><div><span className="text-sm font-bold uppercase tracking-[0.2em] text-[#69ad43]">The business behind the brand</span><h2 className="mt-3 text-3xl font-black tracking-tight text-[#10243e] md:text-5xl">Experience. Trust. Performance.</h2><p className="mt-6 text-lg leading-relaxed text-[#52677d]">J.P Textile, led by <strong className="text-[#10243e]">Jai Prakash Agarwal</strong>, brings over 30 years of experience in manufacturing and trading, with an established presence across Nepal, Assam, Bengal and Bihar.</p><p className="mt-4 text-lg leading-relaxed text-[#52677d]">The business also has more than 15 years of experience in the construction sector. KSO STAR extends this practical, multi-region experience into dependable energy solutions.</p><div className="mt-8 grid grid-cols-2 gap-3">{[{ icon: Globe2, text: 'Nepal · Assam · Bengal · Bihar' }, { icon: Hammer, text: '15+ years construction experience' }, { icon: ShieldCheck, text: 'Manufacturing & trading' }, { icon: Users, text: 'J.P Textile leadership' }].map((item) => <div key={item.text} className="flex items-start gap-3 rounded-xl bg-[#f4f8fb] p-4"><item.icon className="mt-0.5 h-5 w-5 shrink-0 text-[#69ad43]" /><span className="text-sm font-semibold leading-snug text-[#304861]">{item.text}</span></div>)}</div></div><div className="relative"><div className="overflow-hidden rounded-2xl bg-[#10243e] shadow-2xl"><img src="https://images.pexels.com/photos/34221997/pexels-photo-34221997.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Industrial energy facility" className="h-[420px] w-full object-cover opacity-80" /></div><div className="absolute -bottom-8 left-5 right-5 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-white/20 bg-white/20 shadow-xl backdrop-blur-sm sm:grid-cols-4">{stats.map((stat) => <div key={stat.label} className="bg-[#10243e]/95 p-4 text-center"><p className="text-2xl font-black text-[#b8e36d]">{stat.value}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-slate-300">{stat.label}</p></div>)}</div></div></div></div></section>
  );
}
